trigger:
  branches:
    include:
    - master

stages:
- stage: default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-18.04
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: 10.x
      displayName: Install Node.js
    - task: CmdLine@2
      displayName: npm install and test
      inputs:
        script: npm install npm test
    
    - task: gulp@1
      displayName: 'gulp bundel'
      inputs:
        targets: 'bundle'
        arguments: '--ship'

    - task: gulp@1
      displayName: 'gulp package solution'
      inputs:
        targets: 'package-solution'
        arguments: '--ship'

    - script: 'dir sharepoint/solution/*.sppkg'
      displayName: DIR

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(build.artifactstagingdirectory)/drop'
      inputs:
        Contents: 'sharepoint/solution/*.sppkg'
        TargetFolder: '$(build.artifactstagingdirectory)/drop'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifacts: drop'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
